### ISSUE TITLE
feat/fischer mergen

### ISSUE THREAD

**Issue by Klausmd5** [htl-grieskirchen-core/plugin-polls#26]

**Comment by ungarmichael** [comment]
i glaub ned dass do scho wos gmerged is

**Comment by Klausmd5** [comment]
Guad dass de gmergede pr linked is.

**Comment by ungarmichael** [comment]
sike, hob _show all fields_ ned expanded kopt

**Comment by EinboeckFranz** [comment]
> sike, hob _show all fields_ ned expanded kopt; oba wos woa leicht des für commit wonn a ned in master woa

Mit dem Issue is da feature/fischer mitn master branch gesynct woan, d.h. es is s'Backend usw. am Fischer-Branch aktualisiert woadn.
